<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Models\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="Models\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LagoVista.Core.Networking" />
    <PackageReference Include="LagoVista.Core.Rpc" />
    <PackageReference Include="LagoVista.MediaServices" />
    <PackageReference Include="LagoVista.PDFServices" />
    <PackageReference Include="LagoVista.IoT.DeviceAdmin" />
    <PackageReference Include="QRCoder" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LagoVista.IoT.DeviceManagement.Models\LagoVista.IoT.DeviceManagement.Models.csproj" />
  </ItemGroup>
</Project>
