// --- BEGIN CODE INDEX META (do not edit) ---
// ContentHash: 3142491b91b6308eab07ebf4098e8e68a6bb3008efff745a0c5566efb36473b0
// IndexVersion: 0
// --- END CODE INDEX META ---
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoVista.IoT.DeviceManagement.Rpc.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagoVista.IoT.DeviceManagement.Rpc.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;$type&quot;: &quot;LagoVista.IoT.DeviceManagement.Core.Models.DeviceRepository, LagoVista.IoT.DeviceManagement.Models&quot;,
        ///    &quot;DatabaseName&quot;: &quot;dev&quot;,
        ///    &quot;EntityType&quot;: &quot;DeviceRepository&quot;,
        ///    &quot;IsPublic&quot;: false,
        ///    &quot;OwnerOrganization&quot;: {
        ///      &quot;$type&quot;: &quot;LagoVista.Core.Models.EntityHeader, LagoVista.Core&quot;,
        ///      &quot;Id&quot;: &quot;C8AD4589F26842E7A1AEFBAEFC979C9B&quot;,
        ///      &quot;Text&quot;: &quot;Software Logistics&quot;
        ///    },
        ///    &quot;RepositoryType&quot;: {
        ///      &quot;$type&quot;: &quot;LagoVista.Core.Models.EntityHeader`1[[LagoVista.IoT.DeviceManagement.C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeviceRepository {
            get {
                return ResourceManager.GetString("DeviceRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$type&quot;: &quot;System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib&quot;,
        ///  &quot;__message_id&quot;: &quot;9104721a-a0f6-4135-93a0-96d751a73ec5&quot;,
        ///  &quot;__correlation_id&quot;: &quot;e0926fe5-06c1-4c2b-9ee8-c2fe681e9879&quot;,
        ///  &quot;__message_path&quot;: &quot;LagoVista.IoT.DeviceManagement.Core.Repos.IDeviceMediaRepoRemote/AddMediaAsync/&quot;,
        ///  &quot;__instance_id&quot;: &quot;9e88c7f6b5894dbfb3bc09d20736705e&quot;,
        ///  &quot;__organization_id&quot;: &quot;c8ad4589f26842e7a1aefbaefc979c9b&quot;,
        ///  &quot;__re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jsonbug {
            get {
                return ResourceManager.GetString("jsonbug", resourceCulture);
            }
        }
    }
}
